### ISSUE TITLE
SymmetricDS don't sync

### ISSUE THREAD

**Issue by truongnt** [onaio/Reveal-Thailand#17]
Sound like Symmetric stop sync for 2 weeks

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/2433196/215449504-f720df0d-04bf-409f-8ee1-44e3fe0d1959.png)

**Comment by AngelaKabari** [comment]
I confirm that we have received this ticket @truongnt and are taking action.

**Comment by AngelaKabari** [comment]
Hello @truongnt 

The failure of SymmetricDS syncing was caused by an issue with the ETL state machine on Nifi, which occurred on 11th January. It needed a reset which we performed and the issue has now been resolved, and the data is now streaming as it should.

Please take a look and confirm this has been satisfactorily addressed?

**Comment by truongnt** [comment]
Thanks

**Comment by HusnaHariz** [comment]
For context, the root cause of this issue was related to the NiFi training that was conducted on 11th Jan. One of the process groups that was used to showcase ingestion of data from OpenSRP during the training required the processor states (id cursor) to be reset to the last pulled in record so at to prevent a complete re-ingestion of the OpenSRP records. We accidentally forgot to do this after the training was completed, but completed the task after this issue was raised. The root cause has been addressed and will not occur again.
